"""EMBEDHUNT AI — Tier 1 interview bank generator.

Emits backend/data/interview_banks/<subrole>.json from the reviewed Tier-1
question document (14 subroles, 168 questions). Source of truth for the data
files — edit here, re-run, re-seed (seeding is idempotent).
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "backend" / "data" / "interview_banks"

T, B, S = "technical", "behavioral", "system_design"
J, M, SR = "junior", "mid", "senior"

# subrole_code: (domain_code, [(question, category, difficulty, guideline)])
BANKS: dict[str, tuple[str, list]] = {
"backend_engineer": ("software_it", [
 ("Explain the difference between SQL and NoSQL databases and when you'd choose each.", T, M,
  "Should cover consistency vs. flexibility trade-offs, schema rigidity, and give a concrete use case for each."),
 ("How does HTTPS/TLS secure data in transit between client and server?", T, M,
  "Should mention the TLS handshake, cipher suite negotiation, and certificate verification, not just 'it encrypts data'."),
 ("What is database indexing and how does it affect read vs. write performance?", T, M,
  "Should explain B-tree indexing, faster reads at the cost of slower writes and extra storage."),
 ("Design a rate limiter for a public API. What algorithms would you consider?", T, SR,
  "Should discuss token bucket vs. sliding window, distributed rate-limiting via Redis, and trade-offs."),
 ("How would you design a URL shortener service?", T, SR,
  "Should cover ID generation (base62/hashing), read-heavy caching strategy, and collision handling."),
 ("Explain idempotency and why it matters for payment or retry-prone APIs.", T, M,
  "Should define idempotent operations and describe idempotency keys for safe retries."),
 ("How do virtual threads (e.g. in Java) change concurrency patterns vs. traditional thread pools?", T, SR,
  "Should discuss lightweight concurrency, reduced context-switch overhead, and where they still don't help (CPU-bound work)."),
 ("Design a highly available payment webhook processor.", S, SR,
  "Should cover at-least-once delivery, deduplication, dead-letter queues, and retry backoff."),
 ("What's the difference between horizontal and vertical scaling?", T, J,
  "Should give clear definitions and a real trade-off (cost, complexity, single point of failure)."),
 ("Tell me about a production bug you owned end-to-end.", B, M,
  "Look for STAR structure: how it was detected, root-caused, fixed, and what monitoring was added after."),
 ("How would you approach diagnosing a service that is randomly timing out under load?", T, SR,
  "Should mention checking connection pool exhaustion, GC pauses, downstream dependency latency, and tracing."),
 ("Describe a system design decision where you traded consistency for availability, or vice versa.", B, SR,
  "Look for CAP theorem understanding applied to a real scenario, not just textbook recitation."),
]),
"frontend_engineer": ("software_it", [
 ("Explain the virtual DOM and why it improves rendering performance.", T, M,
  "Should explain diffing/reconciliation, not just 'it's faster'."),
 ("What's the difference between controlled and uncontrolled components in React?", T, M,
  "Should tie the answer to where form state lives and give a concrete example."),
 ("How would you optimize a page with a large, slow-rendering list?", T, SR,
  "Should mention windowing/virtualization, memoization, and avoiding unnecessary re-renders."),
 ("Explain the CSS box model and common flexbox vs. grid use cases.", T, M,
  "Should distinguish 1D (flexbox) vs. 2D (grid) layout problems with examples."),
 ("What are Web Vitals (LCP, CLS, INP) and why do they matter?", T, M,
  "Should connect each metric to a real user-perceived performance problem."),
 ("How do you handle state management in a large React application?", T, SR,
  "Should discuss local vs. global state, when to reach for a state library vs. context, and trade-offs."),
 ("What is debouncing vs. throttling, and when would you use each?", T, M,
  "Should give a concrete UI example for each — e.g. search input debounce vs. scroll-handler throttle."),
 ("How would you make a data-heavy dashboard accessible to screen reader users?", T, SR,
  "Should mention ARIA roles, keyboard navigation, and semantic HTML, not just alt text."),
 ("Tell me about a time you had to push back on a design that wasn't technically feasible.", B, M,
  "Look for concrete collaboration with design/product, not just complaining about designers."),
 ("What's the difference between == and === in JavaScript?", T, J,
  "Should explain type coercion clearly with an example."),
 ("Design a component library that's reused across multiple product teams.", S, SR,
  "Should cover versioning, theming/design tokens, and backward compatibility strategy."),
 ("Describe a time a performance issue turned out to be caused by something unexpected.", B, SR,
  "Look for real debugging methodology — profiling tools used, not guesswork."),
]),
"full_stack_engineer": ("software_it", [
 ("Walk me through how you'd design and build a feature from database to UI.", T, M,
  "Should show ownership across layers: schema design, API contract, frontend consumption, and testing."),
 ("REST vs. GraphQL — when would you pick one over the other?", T, M,
  "Should cover over/under-fetching, caching complexity, and team familiarity as real trade-offs."),
 ("How do you keep frontend and backend API contracts in sync as both evolve?", T, SR,
  "Should mention OpenAPI/schema-first design, versioning, and contract testing."),
 ("How would you design authentication for a full-stack app (session vs. token-based)?", T, M,
  "Should compare cookie/session auth vs. JWT, and mention refresh-token handling."),
 ("A feature works locally but fails in production — how do you debug across the stack?", T, SR,
  "Should describe a systematic approach: logs, environment diffs, network tab, and reproducing with prod-like data."),
 ("Tell me about a time you had to make a trade-off between shipping fast and doing it right.", B, M,
  "Look for a reasoned decision with awareness of technical debt incurred, not just 'I shipped fast'."),
 ("How do you approach testing a full-stack feature — what layers do you test and how?", T, M,
  "Should mention unit, integration, and end-to-end tests with a sensible pyramid, not 100% e2e."),
 ("How would you structure a monorepo for a full-stack app with shared types?", T, SR,
  "Should discuss shared type generation, build tooling, and CI considerations."),
 ("What happens between typing a URL and seeing a rendered page?", T, J,
  "Should cover DNS resolution, TCP/TLS handshake, HTTP request, server response, and rendering."),
 ("Describe a cross-team project where you had to align frontend, backend, and product.", B, SR,
  "Look for communication and scoping skills, not just technical execution."),
 ("How do you handle environment configuration across dev/staging/production?", T, M,
  "Should mention environment variables, secrets management, and avoiding hardcoded config."),
 ("Design a notification system that spans backend events and real-time frontend updates.", S, SR,
  "Should cover WebSockets/SSE vs. polling, and how backend events trigger delivery."),
]),
"mobile_developer": ("software_it", [
 ("Explain the app lifecycle on your primary platform and how you handle state during backgrounding.", T, M,
  "Should show understanding of lifecycle callbacks and saving/restoring state correctly."),
 ("How do you design an app to work well with intermittent or no connectivity?", T, M,
  "Should mention local caching, optimistic UI updates, and sync-on-reconnect strategies."),
 ("How would you diagnose and fix a memory leak in a mobile app?", T, SR,
  "Should mention profiling tools (Android Profiler/Instruments) and common leak sources like retained contexts/closures."),
 ("How do you manage state in a Flutter or React Native app at scale?", T, M,
  "Should discuss a chosen state management approach and why, with trade-offs acknowledged."),
 ("How would you reduce app startup time?", T, SR,
  "Should mention lazy initialization, reducing main-thread work at launch, and measuring with real profiling."),
 ("How do push notifications work end-to-end on your platform?", T, M,
  "Should describe the device token registration, push service (FCM/APNs), and app-side handling."),
 ("Tell me about a time you had to support both Android and iOS with limited resources.", B, M,
  "Look for prioritization reasoning and awareness of platform-specific trade-offs."),
 ("How do you handle secure local storage of sensitive data (tokens, credentials)?", T, SR,
  "Should mention Keychain/Keystore usage, not storing secrets in plain SharedPreferences/UserDefaults."),
 ("What's the difference between a native app, a hybrid app, and a cross-platform framework app?", T, J,
  "Should give a clear, correct distinction with examples of each."),
 ("How would you structure automated testing for a mobile app (unit, widget/UI, integration)?", T, SR,
  "Should show a sensible testing pyramid adapted for mobile constraints."),
 ("Describe how you handled a critical crash reported in production.", B, SR,
  "Look for use of crash reporting tools, triage process, and hotfix/rollback strategy."),
 ("How do you optimize battery usage for an app that needs background location updates?", T, M,
  "Should mention adaptive location accuracy, batching updates, and platform-specific background limits."),
]),
"ai_ml_engineer": ("software_it", [
 ("Explain how RAG works and why you'd choose it over fine-tuning for a knowledge-heavy task.", T, M,
  "Should describe retriever + generator architecture and note fine-tuning is brittle for frequently-changing facts."),
 ("Explain self-attention and why transformers process sequences in parallel.", T, M,
  "Should describe query/key/value mechanics at a conceptual level without requiring the full paper."),
 ("How would you evaluate whether an LLM-based feature is production-ready?", T, SR,
  "Should mention faithfulness/groundedness checks, human eval, offline eval sets, and monitoring for drift."),
 ("A model gives confident but factually wrong answers in a high-risk context. How do you investigate and mitigate this?", T, SR,
  "Should discuss root-causing (retrieval gap vs. model gap), grounding via citations, and guardrails — not just 'add more data'."),
 ("What's the difference between fine-tuning and prompt engineering, and when is each appropriate?", T, M,
  "Should cover cost, data requirements, and that prompting is usually the first lever to pull."),
 ("Design a customer-support AI agent with tool use and cost controls.", S, SR,
  "Should cover intent routing, tool-calling guardrails, token budget management, and escalation to a human."),
 ("Explain the bias-variance trade-off with a concrete example.", T, M,
  "Should connect the concept to overfitting/underfitting with a practical illustration."),
 ("How do LoRA/QLoRA reduce the cost of fine-tuning large models?", T, SR,
  "Should explain low-rank adapter updates vs. full-parameter fine-tuning and the memory savings."),
 ("How would you choose between a vector database and a traditional database with a vector extension?", T, M,
  "Should weigh scale, latency requirements, and operational simplicity."),
 ("Describe a time a model performed well offline but poorly in production.", B, SR,
  "Look for awareness of train/serve skew, data drift, and how they diagnosed the gap."),
 ("Explain precision, recall, and F1 score with an example where accuracy alone would mislead.", T, J,
  "Should use a class-imbalance example (e.g. fraud detection) to show why accuracy fails."),
 ("How do you control inference cost and latency in an LLM-backed product at scale?", T, SR,
  "Should mention model tiering/routing, caching, batching, and prompt-length optimization."),
]),
"data_scientist": ("software_it", [
 ("How would you design an A/B test for a new feature, end to end?", T, M,
  "Should cover hypothesis definition, sample size/power calculation, randomization, and guardrail metrics."),
 ("Explain p-value and a common misinterpretation of it.", T, M,
  "Should give the correct statistical definition and flag the common 'probability the null is true' misconception."),
 ("A metric moved significantly after a launch — how do you determine if it's causal?", T, SR,
  "Should discuss confounders, seasonality, and structured causal analysis vs. just correlation."),
 ("Write a SQL query (verbally describe) to find the second-highest salary per department.", T, M,
  "Should reason through window functions (RANK/DENSE_RANK) or a correlated subquery approach."),
 ("What's the difference between correlation and causation, with a business example?", T, M,
  "Should give a concrete example (e.g. ice cream sales and drowning) and explain the confound."),
 ("How would you detect and handle data leakage in a predictive model?", T, SR,
  "Should describe checking for target-derived features, time-based leakage, and proper train/test splitting."),
 ("Tell me about a time your analysis changed a business decision.", B, M,
  "Look for a concrete story with a measurable outcome, not just 'I made a dashboard'."),
 ("How do you choose which metric to optimize when multiple stakeholders want different things?", T, SR,
  "Should show framing around a North Star metric plus guardrails, and stakeholder alignment process."),
 ("What's the difference between a left join and an inner join?", T, J,
  "Should give a clear, correct explanation with an example."),
 ("How do you handle missing data in a dataset before modeling?", T, M,
  "Should discuss multiple approaches (imputation, dropping, flagging) and when each is appropriate."),
 ("Describe a time you had to explain a complex analysis to a non-technical stakeholder.", B, SR,
  "Look for genuine simplification skill, not just 'I used simpler words'."),
 ("How would you design an experiment when random assignment isn't possible?", T, SR,
  "Should mention quasi-experimental methods like diff-in-diff or matching."),
]),
"devops_sre_engineer": ("software_it", [
 ("Explain the difference between rolling, blue-green, and canary deployment strategies.", T, M,
  "Should describe risk/rollback trade-offs for each, not just definitions."),
 ("What are SLIs, SLOs, and error budgets, and how do they relate?", T, M,
  "Should explain error budget as the allowed unreliability derived from the SLO, driving release-pace decisions."),
 ("Walk me through how you'd design a CI/CD pipeline for a microservices app.", T, SR,
  "Should cover build/test/deploy stages, artifact versioning, and safe rollback mechanisms."),
 ("A pod keeps getting OOMKilled in Kubernetes — how do you diagnose and fix it?", T, SR,
  "Should mention checking resource requests/limits, memory profiling the app, and reviewing recent changes."),
 ("What's the benefit of Infrastructure as Code, and what problems can it still cause if misused?", T, M,
  "Should mention reproducibility/auditability, and drift or state-file conflicts as real risks."),
 ("Walk me through how you handled a major production incident, from detection to postmortem.", B, SR,
  "Look for a structured incident process: detection, mitigation, root cause, and blameless postmortem."),
 ("How does horizontal pod autoscaling decide when to scale, and what metric would you use?", T, M,
  "Should mention CPU/memory or custom metrics, and note that scaling on the wrong metric causes thrashing."),
 ("How would you reduce alert fatigue for an on-call rotation?", T, SR,
  "Should mention tuning alert thresholds, alerting on symptoms not causes, and escalation policies."),
 ("What's the difference between a container and a virtual machine?", T, J,
  "Should explain shared kernel vs. full OS virtualization clearly."),
 ("How do you approach zero-downtime database migrations?", T, SR,
  "Should mention backward-compatible schema changes, phased rollout, and dual-write strategies where needed."),
 ("Tell me about a time you automated away a recurring manual task.", B, M,
  "Look for genuine toil reduction with a measurable time/error impact."),
 ("How would you design a monitoring stack for a new service from scratch?", T, SR,
  "Should mention metrics, structured logs, distributed tracing, and dashboards tied to real user impact."),
]),
"cloud_engineer": ("software_it", [
 ("Explain the difference between a public and private subnet in a VPC.", T, M,
  "Should describe routing to an internet gateway vs. NAT gateway and typical use cases for each."),
 ("What's the principle of least privilege and how do you apply it with IAM?", T, M,
  "Should describe scoped roles/policies over broad admin access, with a concrete example."),
 ("How would you design a multi-region architecture for disaster recovery?", T, SR,
  "Should discuss RTO/RPO trade-offs, active-active vs. active-passive, and data replication strategy."),
 ("When would you choose serverless (Lambda/Functions) over containers or VMs?", T, SR,
  "Should weigh cold starts, execution time limits, and cost-at-scale trade-offs honestly."),
 ("How do you approach reducing cloud costs without hurting reliability?", T, M,
  "Should mention right-sizing, reserved/spot instances, and identifying idle resources — not just 'turn things off'."),
 ("How would you secure a publicly exposed API endpoint end to end?", T, SR,
  "Should cover WAF, rate limiting, authentication, and network-level restrictions together."),
 ("Describe a time you had to respond to a security incident in a cloud environment.", B, SR,
  "Look for a structured response: containment, root cause, and remediation, not panic-driven fixes."),
 ("What's the difference between a load balancer and an API gateway?", T, M,
  "Should clarify overlapping but distinct responsibilities (traffic distribution vs. request routing/auth/transformation)."),
 ("What is auto-scaling and what metric would trigger it in a typical web app?", T, J,
  "Should explain the concept and give a sensible metric like CPU utilization or request queue depth."),
 ("How do you manage secrets (API keys, DB credentials) in a cloud-native application?", T, SR,
  "Should mention a secrets manager, rotation policy, and avoiding secrets in code/config files."),
 ("Tell me about a migration you led from on-prem or one cloud provider to another.", B, M,
  "Look for planning around downtime, data migration validation, and rollback plans."),
 ("How would you design for high availability across availability zones?", T, SR,
  "Should mention distributing resources across AZs, health checks, and automated failover."),
]),
"cybersecurity_engineer": ("software_it", [
 ("Explain SQL injection and how to prevent it.", T, M,
  "Should describe the attack mechanism and mandate parameterized queries/prepared statements as the fix, not just input sanitization."),
 ("What's the difference between symmetric and asymmetric encryption, and where is each used?", T, M,
  "Should give correct definitions and real use cases (TLS handshake uses both, for example)."),
 ("Walk me through how you'd threat-model a new feature before it ships.", T, SR,
  "Should mention identifying assets, trust boundaries, and using a structured framework like STRIDE."),
 ("A server is showing signs of compromise — walk me through your incident response.", T, SR,
  "Should follow a structured process: identify, contain, eradicate, recover, and document lessons learned."),
 ("Explain cross-site scripting (XSS) and the difference between stored and reflected XSS.", T, M,
  "Should distinguish persistence of the payload and give a mitigation (output encoding, CSP)."),
 ("How would you design a zero-trust network architecture?", T, SR,
  "Should mention 'never trust, always verify', micro-segmentation, and continuous authentication."),
 ("Describe a vulnerability you found and how you responsibly disclosed or remediated it.", B, SR,
  "Look for a structured, ethical process — not war stories that suggest reckless testing."),
 ("What's the OWASP Top 10 and why does it matter for engineering teams, not just security teams?", T, M,
  "Should name several categories correctly and connect it to secure coding practices, not just a checklist."),
 ("What's the difference between authentication and authorization?", T, J,
  "Should give a clear, correct distinction with an example."),
 ("How do you balance security requirements against developer velocity in a fast-moving team?", T, SR,
  "Should show pragmatic judgment — e.g. shifting security left with tooling, not blocking every release manually."),
 ("What is a man-in-the-middle attack and how does TLS prevent it?", T, M,
  "Should explain certificate validation and the handshake's role in preventing interception."),
 ("Tell me about a time you had to convince a team to fix a security issue they didn't see as urgent.", B, M,
  "Look for risk communication skill — translating technical risk into business impact."),
]),
"qa_automation_engineer": ("software_it", [
 ("Explain the test pyramid and why too many end-to-end tests is a problem.", T, M,
  "Should describe the unit/integration/e2e balance and note e2e tests are slow and flaky at scale."),
 ("How do you design test cases for a feature with no formal spec?", T, M,
  "Should mention boundary value analysis, equivalence partitioning, and clarifying ambiguity with stakeholders."),
 ("How would you handle flaky tests in a CI pipeline?", T, SR,
  "Should discuss root-causing (timing/race conditions, test isolation) rather than just retrying or skipping."),
 ("What's the difference between smoke testing, regression testing, and exploratory testing?", T, M,
  "Should give clear, distinct definitions and when each is used in a release cycle."),
 ("How would you design an automated test suite for a REST API?", T, SR,
  "Should cover status codes, schema validation, auth scenarios, and negative/edge cases, not just happy-path checks."),
 ("Tell me about a critical bug you found that others missed — how did you find it?", B, M,
  "Look for a systematic testing approach, not luck, and how it changed the team's process."),
 ("How do you decide what to automate vs. keep manual/exploratory?", T, SR,
  "Should weigh repetition frequency, stability of the feature, and ROI of automation effort."),
 ("What makes a good bug report?", T, J,
  "Should include reproduction steps, expected vs. actual behavior, environment details, and severity."),
 ("How would you performance-test an API endpoint before a major traffic event?", T, M,
  "Should mention load vs. stress vs. soak testing and identifying the actual bottleneck, not just hitting it with traffic."),
 ("Describe a time QA and engineering disagreed on release readiness.", B, SR,
  "Look for data-driven advocacy and a collaborative resolution, not just 'I blocked the release'."),
 ("How do you integrate automated tests into a CI/CD pipeline without slowing releases down?", T, SR,
  "Should mention parallelization, tiered test suites (fast smoke tests gate merge, full suite gates release)."),
 ("What's the difference between mocking and stubbing in test design?", T, M,
  "Should give a precise distinction with an example of when each is appropriate."),
]),
"database_engineer_dba": ("software_it", [
 ("Explain ACID properties with a real transaction example.", T, M,
  "Should define atomicity, consistency, isolation, durability and tie each to a concrete transaction scenario."),
 ("How would you optimize a slow-running query?", T, M,
  "Should mention EXPLAIN plans, index usage, and identifying full table scans before rewriting the query."),
 ("Explain the difference between horizontal partitioning (sharding) and vertical partitioning.", T, SR,
  "Should give correct definitions and a scenario where each is preferable."),
 ("How would you design a backup and disaster-recovery strategy for a production database?", T, SR,
  "Should cover RPO/RTO targets, backup frequency, and testing restore procedures — not just 'we take backups'."),
 ("What are the trade-offs of adding an index to a frequently written table?", T, M,
  "Should explain the write-amplification cost against the read-speed benefit."),
 ("Explain database replication and the difference between synchronous and asynchronous replication.", T, SR,
  "Should discuss the consistency vs. latency trade-off of each."),
 ("Describe a time you had to recover from a production data incident.", B, SR,
  "Look for a calm, methodical recovery process and what safeguards were added afterward."),
 ("What's the difference between a primary key and a unique key?", T, J,
  "Should give a clear, correct distinction including NULL handling."),
 ("How do you handle schema migrations on a live production database with zero downtime?", T, M,
  "Should mention backward-compatible changes, phased rollout, and avoiding long table locks."),
 ("How would you diagnose a database experiencing connection pool exhaustion?", T, SR,
  "Should mention checking for long-running/unclosed connections and application-side pool configuration."),
 ("Tell me about a time you had to push back on an application design that would have hurt database performance.", B, M,
  "Look for proactive collaboration with engineering, not reactive firefighting."),
 ("What's the difference between optimistic and pessimistic locking, and when would you use each?", T, SR,
  "Should tie the choice to contention frequency in the actual workload."),
]),
"embedded_software_engineer": ("embedded_engineering", [
 ("Explain the difference between a preemptive and cooperative RTOS scheduler.", T, M,
  "Should describe context-switch triggering and give a real-time responsiveness trade-off."),
 ("What is priority inversion and how do RTOSes typically prevent it?", T, M,
  "Should describe the scenario and mention priority inheritance/ceiling protocols as the fix."),
 ("Explain the AUTOSAR layered architecture (application, RTE, BSW, MCAL).", T, SR,
  "Should correctly describe the layering and how it enables hardware abstraction and reuse."),
 ("How would you debug an intermittent hard fault on an embedded target?", T, SR,
  "Should mention stack overflow checks, memory corruption, and using a debugger/fault status registers systematically."),
 ("What's the difference between CAN and LIN bus, and when would you use each?", T, M,
  "Should mention cost, speed, and topology differences with correct use-case reasoning."),
 ("Explain ISO 26262 ASIL levels and how they influence software development rigor.", T, SR,
  "Should describe risk-based classification (QM to ASIL D) and how it drives testing/review requirements."),
 ("What is a memory leak's equivalent risk in embedded C, given no garbage collector?", T, M,
  "Should discuss manual memory management risks, static allocation preference, and heap fragmentation."),
 ("Describe a time you had to debug a issue that only appeared in the field, not in testing.", B, SR,
  "Look for systematic root-causing under real production constraints (limited logging, hardware access)."),
 ("What's the difference between volatile and const in C, and when must you use volatile?", T, J,
  "Should correctly explain volatile's role in preventing compiler optimization on hardware/ISR-modified variables."),
 ("How does MISRA C improve safety in embedded code, and what's a rule you disagree with or find limiting?", T, SR,
  "Should show real working knowledge of MISRA rules, not just 'it's a coding standard'."),
 ("Explain the boot sequence of an embedded system from power-on to application execution.", T, M,
  "Should describe bootloader stages, vector table setup, and jumping to application code."),
 ("How would you optimize an embedded application for low power consumption?", T, SR,
  "Should mention sleep modes, clock gating, and minimizing active peripheral time."),
]),
"electronics_vlsi_fpga_engineer": ("embedded_engineering", [
 ("Explain the difference between combinational and sequential logic with an example.", T, M,
  "Should give correct definitions and a clocking example distinguishing the two."),
 ("What is clock domain crossing and why is it a common source of bugs?", T, SR,
  "Should explain metastability risk and mention synchronizer techniques as mitigation."),
 ("Walk me through the ASIC design flow from RTL to GDSII.", T, SR,
  "Should correctly sequence synthesis, place & route, timing closure, and verification stages."),
 ("What's the difference between an FPGA and an ASIC, and when would you choose each?", T, M,
  "Should weigh time-to-market, unit cost at volume, and reconfigurability trade-offs."),
 ("Explain setup and hold time violations and how you'd fix a timing closure issue.", T, SR,
  "Should describe the timing constraint concept and practical fixes (pipelining, retiming, constraint adjustment)."),
 ("What is UVM and why is it used for verification instead of simple testbenches?", T, M,
  "Should mention reusability, constrained-random verification, and coverage-driven methodology."),
 ("Describe a time a design passed simulation but failed on silicon — how did you debug it?", B, SR,
  "Look for structured bring-up debugging: scope/logic analyzer use, isolating the failure domain."),
 ("What's the difference between synchronous and asynchronous resets?", T, J,
  "Should give a correct distinction and a trade-off (timing vs. glitch sensitivity)."),
 ("How do you approach power optimization in a digital design?", T, SR,
  "Should mention clock gating, power gating, and voltage/frequency scaling."),
 ("Explain signal integrity issues that can arise on a high-speed PCB.", T, M,
  "Should mention reflections, crosstalk, and impedance matching at a conceptual level."),
 ("What is DFT (design for test) and why is it added to a chip design?", T, SR,
  "Should mention scan chains and built-in self-test enabling post-fabrication testing."),
 ("Explain the difference between Verilog blocking and non-blocking assignments.", T, M,
  "Should correctly explain simulation execution order differences and when to use each."),
]),
"network_engineer": ("software_it", [
 ("Explain the OSI model layers and give a real protocol example for each of the top 4 layers.", T, M,
  "Should correctly map layers to protocols (e.g. HTTP-application, TCP-transport, IP-network, Ethernet-datalink)."),
 ("What's the difference between TCP and UDP, and when would you use each?", T, M,
  "Should cover reliability/ordering trade-offs with concrete use cases (file transfer vs. video streaming)."),
 ("Explain how BGP determines the best path between autonomous systems.", T, SR,
  "Should mention path attributes and policy-based route selection, not just 'shortest path'."),
 ("What is a VLAN and why would you segment a network into multiple VLANs?", T, M,
  "Should mention broadcast domain isolation, security segmentation, and traffic management."),
 ("Walk me through troubleshooting a scenario where a user can't reach a specific website but other sites work fine.", T, SR,
  "Should follow a structured process: DNS check, routing check, firewall/ACL check, isolating the failure point."),
 ("Explain the DNS resolution process from typing a domain name to getting an IP address.", T, M,
  "Should describe recursive resolver, root/TLD/authoritative server steps correctly."),
 ("Describe a time you diagnosed an intermittent network outage.", B, SR,
  "Look for systematic use of monitoring tools and packet captures, not guesswork."),
 ("What's the difference between a stateful and stateless firewall?", T, SR,
  "Should explain connection-tracking vs. rule-only filtering with an example of what each catches/misses."),
 ("What's the difference between a switch and a router?", T, J,
  "Should give a clear, correct distinction (layer 2 vs. layer 3 forwarding)."),
 ("How would you design network redundancy to avoid a single point of failure?", T, SR,
  "Should mention redundant links, protocols like STP/HSRP/VRRP, and failover testing."),
 ("Explain how a VPN provides secure remote access.", T, M,
  "Should mention tunneling and encryption, and distinguish site-to-site vs. remote-access VPNs."),
 ("Tell me about a time you had to explain a network issue to a non-technical stakeholder.", B, M,
  "Look for genuine simplification skill and clear impact communication."),
]),
}


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    total = 0
    for subrole, (domain_code, questions) in BANKS.items():
        doc = {
            "domain_code": domain_code,
            "subrole_code": subrole,
            "questions": [
                {"question_text": q, "category": cat, "difficulty": diff,
                 "model_answer_guideline": guide, "source_type": "curated"}
                for q, cat, diff, guide in questions
            ],
        }
        (OUT / f"{subrole}.json").write_text(json.dumps(doc, indent=1))
        total += len(questions)
        print(f"  {subrole}.json: {len(questions)} questions ({domain_code})")
    print(f"Generated {len(BANKS)} files, {total} questions total.")


if __name__ == "__main__":
    main()
