"""EMBEDHUNT AI — Company-asked question bank.

Real questions reported from embedded interviews at tier-1 silicon companies
(Qualcomm / AMD style panels). Curated from raw interview reports: deduplicated,
cleaned up, tagged by skill, and given grading hints. Project-specific prompts
("explain your second project") are generalised into reusable forms.

Every entry: ``q, skill, type, difficulty, expected`` (+ optional
``follow_ups``). ``source`` is always ``company_asked`` so the UI can badge
these as "asked in real interviews".
"""
from __future__ import annotations


def _q(q: str, skill: str, type_: str, difficulty: str, expected: str,
       follow_ups: list[str] | None = None) -> dict:
    d = {"q": q, "skill": skill, "type": type_, "difficulty": difficulty,
         "expected": expected, "source": "company_asked"}
    if follow_ups:
        d["follow_ups"] = follow_ups
    return d


COMPANY_QUESTIONS: list[dict] = [
    # ── C: pointers & memory ─────────────────────────────────────────────
    _q("What is a function pointer? Write the prototype for one and show where you would use it.",
       "c", "core", "medium",
       "ret_type (*name)(args); callbacks, ISR vector tables, state machines, driver ops tables",
       ["How does a table of function pointers replace a switch statement?",
        "What goes wrong if the signature of the assigned function doesn't match?"]),
    _q("Reverse a string in place without using a temporary variable and without XOR swap.",
       "c", "coding", "medium",
       "Two-index walk with arithmetic swap (a=a+b; b=a-b; a=a-b) or single-char temp debate; discuss overflow caveat"),
    _q("What is a dangling pointer, what is a memory leak, and how do you avoid each?",
       "c", "core", "medium",
       "Dangling: use-after-free/returned stack address — set to NULL, ownership rules. Leak: lost reference — single-owner discipline, cleanup paths, static analysis"),
    _q("Explain dynamic memory allocation in C: malloc, calloc, realloc, free — and their failure modes.",
       "c", "core", "easy",
       "Heap allocation APIs; calloc zeroes, realloc may move, free exactly once; check NULL returns"),
    _q("What is structure padding? Show a struct's size with and without padding and explain how to control it.",
       "c", "core", "medium",
       "Alignment-driven holes; reorder members largest-first, #pragma pack / __attribute__((packed)) and their access-cost tradeoffs",
       ["Why can packed structs be slower or even fault on some cores?"]),
    _q("Write an enum, and a struct containing an int, a bool and a char array of 10 — then compute its size on a 32-bit machine.",
       "c", "coding", "easy",
       "sizeof with padding: 4 + 1 + 10 → padded to 16 typically; explain each hole"),
    _q("Copy N bytes between two pointers and prove the copy is correct.",
       "c", "coding", "easy",
       "memcpy or loop; verify with memcmp; discuss overlap → memmove"),
    _q("A user's credential (e.g. account number) was heap-allocated. Free it so it can never be recovered later — what does plain free() get wrong?",
       "c", "applied", "hard",
       "free() doesn't erase; memset_s/explicit_bzero before free (plain memset can be optimised away), then NULL the pointer",
       ["Why can the compiler legally delete a memset just before free?"]),
    _q("What is the difference between struct, union and enum? When would a driver use a union?",
       "c", "core", "easy",
       "Struct: all members; union: shared storage/overlay (register views, protocol variants); enum: named integer constants"),
    _q("How is the value 130 stored in a signed char, and what value do you read back? Explain.",
       "c", "core", "medium",
       "8-bit two's complement: 130 → 0x82 → -126; signed overflow/implementation-defined conversion discussion"),
    _q("Explain C storage classes: auto, static, extern, register — with where each lives in memory.",
       "c", "core", "easy",
       "Scope + lifetime + linkage; static locals in .data/.bss, extern declarations vs definitions"),
    _q("Allocate a 2-D array dynamically in C — show two ways and their memory layouts.",
       "c", "coding", "medium",
       "Array of row pointers vs single contiguous block with index math; contiguous is cache/DMA friendly"),
    _q("Convert the string \"132\" to the integer 132 without library functions.",
       "c", "coding", "easy",
       "result = result*10 + (ch - '0'); handle sign, overflow, invalid chars"),
    _q("What is virtual memory, why do we need it when physical memory exists, and what roles do the MMU and page table play?",
       "c", "core", "medium",
       "Per-process address spaces, isolation/protection, demand paging; MMU translates VA→PA via page tables; TLB caches translations",
       ["Where does the page table itself live?", "What happens on a TLB miss vs a page fault?"]),
    _q("Two processes share a memory region. What problems can arise and how do you solve them?",
       "c", "applied", "hard",
       "Races/torn updates and lifetime/cleanup; synchronise with process-shared mutexes/semaphores, define ownership and layout versioning"),

    # ── C: bit manipulation drills ───────────────────────────────────────
    _q("Check whether a number is odd or even using bitwise operators only.",
       "c", "coding", "easy", "n & 1 — LSB test; why % 2 differs for negatives"),
    _q("Add two integers using only bitwise operators.",
       "c", "coding", "medium",
       "Loop: sum = a^b, carry = (a&b)<<1 until carry is 0"),
    _q("Multiply two numbers using only bitwise operators (shift-and-add), reading input from the user.",
       "c", "coding", "medium",
       "Russian-peasant: while b { if (b&1) acc+=a; a<<=1; b>>=1; }"),
    _q("Set, clear and toggle all bits in a given range [start, end] of a 32-bit value, taking the range from the user.",
       "c", "coding", "medium",
       "Build mask ((1u<<(end-start+1))-1)<<start; then |=, &=~, ^=; watch the 32-bit-width edge case"),
    _q("Write a one-line macro that flips the bits in a given range of a word.",
       "c", "coding", "medium",
       "#define FLIP(v,s,e) ((v) ^ ((((1u<<((e)-(s)+1))-1)<<(s)))) — parenthesise every use"),
    _q("Count the number of set bits in an integer — then do it faster than once-per-bit.",
       "c", "coding", "easy",
       "Kernighan x&=x-1 per set bit; lookup table; __builtin_popcount"),
    _q("Given a number, reset every bit that is set at an even bit position and print the new number.",
       "c", "coding", "medium",
       "Mask even positions with 0x55555555 (positions 0,2,4… — clarify convention) and clear: n & ~0x55555555"),
    _q("Convert 10 and 20 to binary and hexadecimal by hand, and show the working.",
       "c", "core", "easy", "10=0b1010=0xA; 20=0b10100=0x14; place-value method"),

    # ── C: array problems ────────────────────────────────────────────────
    _q("Sort an array whose elements are only 0, 1 and 2 — in one pass without counting sort.",
       "c", "coding", "medium",
       "Dutch national flag: low/mid/high pointers, single pass, O(1) space"),
    _q("An unsorted array of size N holds numbers 0..N with one number repeated and one missing. Find both.",
       "c", "coding", "medium",
       "Sum & sum-of-squares equations, or XOR partitioning, or index marking; discuss overflow"),
    _q("Given an array with positive and negative numbers, determine whether any subarray sums to zero.",
       "c", "coding", "medium",
       "Prefix sums + seen-set: repeated prefix (or 0) ⇒ zero-sum subarray; O(n)"),
    _q("Separate even and odd elements of an array without changing their relative order and without an extra array.",
       "c", "coding", "hard",
       "Stable partition in place: insertion-style rotation, O(n²) worst; discuss why O(n)+stable+O(1) space is hard"),
    _q("Find the largest element in an array without sorting; then the second largest in a single pass.",
       "c", "coding", "easy",
       "Track max and second-max with careful update order and duplicate handling"),
    _q("Find the third largest element in an array without sorting.",
       "c", "coding", "medium",
       "Three rolling maxima with strict-duplicate policy; O(n), O(1)"),
    _q("Find the frequency of each letter in a string.",
       "c", "coding", "easy",
       "int count[256] indexed by unsigned char; watch signed-char pitfalls"),
    _q("From a list like [2,3,1,1,2,3,5,5,5,8,9,1,1], print only the non-repeated (unique) elements.",
       "c", "coding", "easy",
       "Frequency count then filter count==1; preserve encounter order"),

    # ── Data structures / linked lists ───────────────────────────────────
    _q("Binary search vs linear search: which is better and why? Name scenarios where binary search cannot be used.",
       "data structures", "core", "easy",
       "O(log n) needs sorted, random-access data; linked lists, unsorted/streaming data, tiny arrays favour linear",
       ["Why is binary search on a linked list pointless even though it's 'sorted'?"]),
    _q("Detect whether a singly linked list contains a loop.",
       "data structures", "coding", "medium",
       "Floyd tortoise/hare; prove termination; find the loop start as a follow-up"),
    _q("Find the middle element of a linked list in one traversal.",
       "data structures", "coding", "easy",
       "Slow/fast pointers; state the even-length convention"),
    _q("Merge two sorted linked lists into one sorted list.",
       "data structures", "coding", "medium",
       "Dummy head + tail append; O(1) extra space; preserve stability"),
    _q("Delete a node from a linked list: at the head, at a given position, and after a given node value.",
       "data structures", "coding", "medium",
       "Pointer-to-pointer or prev tracking; free correctly; edge cases: head, tail, missing"),
    _q("Delete the (n-1)th node of a linked list.",
       "data structures", "coding", "medium",
       "Walk to n-2, relink, free; validate length ≥ n"),
    _q("Reverse a linked list k nodes at a time and state the time and space complexity.",
       "data structures", "coding", "hard",
       "Iterative group reverse with stub links; O(n) time, O(1) space"),
    _q("In a circular linked list, how do you find the 'last' element?",
       "data structures", "coding", "easy",
       "Node whose next is the head; keep a tail pointer to make it O(1)"),
    _q("What are queues and stacks? Give one firmware use case for each.",
       "data structures", "core", "easy",
       "FIFO: ISR-to-task event queues; LIFO: call stack, undo, parser nesting"),

    # ── OS / concurrency ─────────────────────────────────────────────────
    _q("What is a thread, why use threads, and how do threads in one process communicate?",
       "operating systems", "core", "easy",
       "Schedulable execution context sharing address space; shared memory + mutex/condvar, queues; cheaper than processes"),
    _q("Difference between a process and a thread — memory layout, cost, failure isolation.",
       "operating systems", "core", "easy",
       "Own address space vs shared; context-switch cost; one crashing thread kills the process"),
    _q("Multiprocessing vs multithreading — when do you pick each?",
       "operating systems", "core", "medium",
       "Isolation/robustness/multi-core scaling vs shared-state efficiency; embedded: processes for fault containment"),
    _q("Semaphore vs mutex — the real differences, not just 'binary semaphore'.",
       "operating systems", "core", "medium",
       "Ownership + priority inheritance vs signalling counter; who releases; ISR usage rules",
       ["Why must a mutex be released by its taker while a semaphore need not be?"]),
    _q("Spinlock vs mutex: when is spinning correct, and what must you never do while holding a spinlock?",
       "operating systems", "core", "hard",
       "Short critical sections on SMP / IRQ context spin; blocking sleeps — never sleep holding a spinlock"),
    _q("Demonstrate semaphore usage with two threads — write the code.",
       "operating systems", "coding", "medium",
       "sem_init/sem_wait/sem_post producer-consumer skeleton with shared buffer"),
    _q("Explain the IPC mechanisms you know, and write a small pipe example.",
       "operating systems", "coding", "medium",
       "Pipes, FIFOs, shared memory, message queues, sockets, signals; pipe(fd)+fork read/write demo"),
    _q("What is a race condition? Give a concrete embedded example and two distinct fixes.",
       "operating systems", "core", "medium",
       "Unsynchronised RMW on shared state; ISR/task counter example; critical section, atomics, single-writer design"),
    _q("Explain priority inversion with a scenario, and how priority inheritance solves it.",
       "operating systems", "applied", "hard",
       "L holds mutex, M preempts L, H blocks; inheritance boosts L to H's priority; Mars Pathfinder story"),
    _q("Describe the full C compilation process from .c file to executable.",
       "operating systems", "core", "easy",
       "Preprocess → compile → assemble → link; what each stage outputs; where the linker script fits in embedded"),
    _q("Which commands list running processes and kill one?",
       "operating systems", "core", "easy",
       "ps aux / top / pidof; kill -15 then -9; signals difference"),

    # ── Embedded core ────────────────────────────────────────────────────
    _q("What is a bootloader and what are its responsibilities?",
       "bootloader", "core", "medium",
       "Init clocks/RAM, validate/select image, update path, hand off with clean state (VTOR/MSP on Cortex-M)"),
    _q("Walk through the boot sequence of an embedded system from power-on reset to the application running.",
       "bootloader", "core", "hard",
       "ROM → SPL/bootloader stages → clock/DDR init → image verify/load → vector/SP handoff → runtime init → main"),
    _q("How is a ring buffer used inside a driver (e.g. an ADC with interrupts)? Describe the ISR/consumer split.",
       "embedded c", "applied", "medium",
       "ISR produces samples into SPSC ring, task consumes; indices with single writers; overflow policy"),
    _q("As a software engineer, how do you reduce a device's heat purely from software?",
       "low power", "applied", "hard",
       "DVFS, sleep states/tickless idle, duty-cycling peripherals, batching work, avoiding busy-wait, thermal throttling loops",
       ["Which of these help a phone SoC vs a battery MCU?"]),
    _q("What is an SoC? Sketch its internal architecture and explain why SoCs heat up.",
       "soc", "core", "medium",
       "CPU clusters + GPU/DSP/NPU + memory controllers + interconnect + peripherals; dynamic (switching) + leakage power density"),
    _q("Why do mobile phones get hot — what are the main heat sources and mitigations?",
       "soc", "applied", "medium",
       "SoC power density, modem/RF, charging, display; governors, throttling, workload placement (big.LITTLE)"),
    _q("What is a Microcontroller Unit (MCU) and how does it differ from an SoC/MPU?",
       "microcontroller", "core", "easy",
       "Integrated CPU+flash+RAM+peripherals, no MMU typically, runs bare metal/RTOS; MPU/SoC runs rich OS with external memory"),
    _q("What does STM stand for in STM32, and what family is it?",
       "stm32", "core", "easy",
       "STMicroelectronics 32-bit Cortex-M family; naming decodes series/pins/flash"),
    _q("How does a BMS work, and which battery parameters does firmware monitor?",
       "bms", "applied", "medium",
       "Cell voltages, pack current, temperatures, SoC/SoH estimation, balancing, protection FETs, comms (CAN)"),
    _q("Why do batteries heat up during operation and charging?",
       "bms", "core", "medium",
       "I²R losses in internal resistance, electrochemical inefficiency, fast-charge rates; thermal runaway risk management"),
    _q("Explain cryptography basics as used in secure boot, and how you would implement secure boot on your board.",
       "secure boot", "applied", "hard",
       "Hash + asymmetric signature; immutable root verifies next stage; key storage in OTP/fuses; anti-rollback"),
    _q("Explain JTAG and Trace32 in depth — what do they give you beyond printf, and whose product is Trace32?",
       "jtag", "core", "medium",
       "Debug access port: halt/step/registers/memory, flash program; Lauterbach Trace32 adds trace (ETM), scripting, awareness of RTOS",
       ["When is trace the only realistic way to find a bug?"]),
    _q("Why are oscilloscopes used in firmware debugging? Describe a fault you can only find with one.",
       "debugging", "applied", "medium",
       "Electrical truth vs software assumption: signal integrity, timing, glitches, baud drift, I2C stuck bus"),
    _q("What is a CAN analyzer and how do you use it during ECU development?",
       "can", "applied", "medium",
       "Bus capture/decode vs DBC, error-frame stats, replay/simulation of nodes, timing/load analysis"),
    _q("Write a task for an RTOS that reads a sensor periodically and raises an alert when thresholds are crossed.",
       "rtos", "coding", "medium",
       "Periodic task with vTaskDelayUntil, hysteresis on threshold, queue/notification to alert task; no busy-wait"),
    _q("How do you write code snippets around hardware timers — one-shot vs periodic, and what belongs in the callback?",
       "timers", "coding", "medium",
       "Configure prescaler/period, ISR sets flag/notification, defer work; drift-free scheduling from deadlines"),

    # ── Protocols ────────────────────────────────────────────────────────
    _q("Explain how the SPI protocol works on the wire — signals, modes, and a full transfer.",
       "spi", "core", "medium",
       "MOSI/MISO/SCLK/CS, CPOL/CPHA modes, full-duplex shift registers, chip-select framing"),
    _q("Explain how the I2C protocol works — start/stop, addressing, ACK, clock stretching.",
       "i2c", "core", "medium",
       "Open-drain two-wire, 7-bit address + R/W, per-byte ACK, repeated start, stretching, multi-master arbitration"),
    _q("Your I2C driver isn't working. Walk through exactly how you would debug it.",
       "i2c", "applied", "hard",
       "Scope SDA/SCL first: pull-ups, address/ACK presence, stretching; then driver config (speed, addressing), bus recovery (9 clocks)",
       ["What does a missing ACK on the address byte tell you vs on a data byte?"]),
    _q("Write the device-tree node for an SPI controller with a DAC slave attached.",
       "device tree", "coding", "hard",
       "&spiX { status; dac@0 { compatible, reg=<0>, spi-max-frequency, vendor props }; }; explain reg = chip select"),
    _q("How does a user-space application end up talking to firmware/hardware? Explain the complete flow.",
       "linux kernel", "applied", "hard",
       "App → syscall → VFS/subsystem → driver → bus controller → device; interrupts/DMA upward; give one concrete path (e.g. camera or sensor read)"),

    # ── Embedded Linux / Yocto ───────────────────────────────────────────
    _q("What is a device tree, why is it required, and how do you modify it with overlays?",
       "device tree", "core", "hard",
       "Hardware description decoupled from kernel; compatible→probe matching; .dtsi include hierarchy; runtime overlays for hats/mezzanines"),
    _q("What is Yocto, why use it, and which bitbake commands do you actually run?",
       "yocto", "core", "medium",
       "Reproducible custom distro builds; layers/recipes; bitbake image, -c menuconfig, devshell, cleansstate; poky reference distro",
       ["What is the difference between poky, openembedded-core and a layer?"]),
    _q("Explain bitbake and poky in the Yocto ecosystem.",
       "yocto", "core", "medium",
       "bitbake: task scheduler/executor over recipes; poky: reference distribution combining oe-core + bitbake + metadata"),
    _q("You need to add a new tool into your build — when do you extend a Makefile and when do you write a Yocto recipe/bbclass?",
       "yocto", "applied", "hard",
       "Makefile: component-local build logic; recipe: fetch/build/package into image; bbclass: shared build behaviour across recipes"),
    _q("Describe board bring-up: the exact steps you follow on first silicon/board.",
       "bsp", "applied", "hard",
       "Power rails/clocks check, JTAG attach, ROM/bootloader up, DDR init, UART console, kernel+DT boot, peripheral-by-peripheral validation",
       ["What do you do when the board doesn't even give you JTAG?"]),
    _q("Explain top-half and bottom-half interrupt handling in Linux, and the mechanisms for each.",
       "linux kernel", "core", "hard",
       "Hard IRQ minimal work; deferred: softirq/tasklet (atomic) vs workqueue/threaded IRQ (sleepable); why the split exists"),
    _q("What is udev and what does it do when you plug in a device?",
       "linux kernel", "core", "medium",
       "Userspace device manager: uevents → rules → /dev nodes, permissions, module loading triggers"),
    _q("What is a kernel module? How do you load, unload and inspect one?",
       "linux kernel", "core", "easy",
       "Loadable .ko; insmod/modprobe, rmmod, lsmod, modinfo, dmesg for probe logs"),
    _q("When a web application accesses a camera, how does the associated driver get loaded and used?",
       "linux kernel", "applied", "hard",
       "Hotplug uevent → modprobe (modalias) → V4L2 driver probe → /dev/video* via udev → app opens through V4L2/browser media stack"),
    _q("Which Linux distributions do you know, and what makes an embedded distro different?",
       "linux", "core", "easy",
       "Ubuntu/Debian/Fedora/Alpine; embedded: Yocto/Buildroot-built, read-only rootfs, no package manager, size/boot-time focus"),
    _q("How do you grep for a pattern that contains spaces? Give the exact command.",
       "linux", "core", "easy",
       "Quote it: grep \"hello world\" file; add -r -n -i; fixed strings with -F"),
    _q("Which command shows whether a device is mounted properly?",
       "linux", "core", "easy",
       "mount | grep, findmnt, lsblk, df -h — and what each shows"),
    _q("What are Linux file permissions, and how do you change them — including recursively for every file in a directory?",
       "linux", "core", "easy",
       "rwx for user/group/other, octal; chmod 644 file, chmod -R or find -type f -exec chmod for files-only"),
    _q("Delete all files inside a directory without deleting the directory itself.",
       "linux", "core", "easy",
       "rm -rf dir/* (plus dotfiles caveat) or find dir -mindepth 1 -delete; why the find form is safer"),
    _q("Which kernel version are you running and how do you check it?",
       "linux", "core", "easy",
       "uname -r / uname -a; /proc/version; why the version matters for driver APIs"),
    _q("What is Git, which commands do you use daily, and walk through committing and merging your changes into the main repository.",
       "git", "core", "easy",
       "status/add/commit/push, branch/checkout, pull --rebase, merge/PR flow, resolving conflicts; GitHub/GitLab collaboration"),
    _q("What is an API? Explain APIs you have consumed or exposed in a firmware project and why they exist.",
       "misc", "core", "easy",
       "Contract between components; HAL APIs, driver ioctl/sysfs, REST for tooling; stability and abstraction reasons"),
    _q("What is regression testing vs sanity testing? When do you run each?",
       "testing", "core", "easy",
       "Regression: full re-verify after changes; sanity: quick targeted check that a fix/build is rational before deeper testing"),
    _q("Describe how you perform manual testing on an embedded feature — the concrete steps.",
       "testing", "applied", "medium",
       "Setup/preconditions, stimulus, expected vs observed, logs/scope evidence, teardown, defect report with repro"),
    _q("How do you apply patches to a codebase (and to a Yocto recipe)?",
       "git", "applied", "medium",
       "git apply/am, format-patch; Yocto: SRC_URI += file://fix.patch with devtool workflow"),

    # ── C++ (asked in these panels) ──────────────────────────────────────
    _q("What is function overloading and operator overloading? Where is operator overloading genuinely useful?",
       "c++", "core", "medium",
       "Same name different signatures (compile-time); operators for value types (fixed-point, units); why not to overload cleverly"),
    _q("Explain exception handling: try/catch/finally — and what role does 'finally' play when a file fails to open?",
       "c++", "core", "medium",
       "Cleanup guaranteed on both paths; C++ uses RAII instead of finally; Python/Java finally for resource release"),

    # ── Python (as used in embedded tooling/tests) ───────────────────────
    _q("Write a Python program to check whether a given string is a palindrome.",
       "python", "coding", "easy", "s == s[::-1] after normalising; two-pointer alternative"),
    _q("Write a Python program to find all three-, four- and five-character words in a string.",
       "python", "coding", "easy", "re.findall(r'\\b\\w{3,5}\\b', s) or split+len filter"),
    _q("Write a Python program that sorts a list of numbers by the sum of their digits.",
       "python", "coding", "medium", "sorted(nums, key=lambda n: sum(int(d) for d in str(abs(n))))"),
    _q("Accept an integer n and compute n + nn + nnn (digit concatenation).",
       "python", "coding", "easy", "int(s) + int(s*2) + int(s*3) with s=str(n)"),
    _q("Create and display all combinations of letters selecting one letter from each key in a dictionary.",
       "python", "coding", "medium", "itertools.product(*d.values()) and join"),
    _q("Implement the Collatz step: given positive n, print the sequence — n/2 if even, 3n+1 if odd, until 1.",
       "python", "coding", "easy", "while n != 1 loop with parity branch; discuss why termination is conjecture"),
    _q("Write a Python program that creates a file listing the alphabet with three letters per line.",
       "python", "coding", "easy", "string.ascii_lowercase chunked by 3, '\\n'.join, with open(...,'w')"),
    _q("Accept a list of integers, then print its length and its fifth element — handling the too-short case.",
       "python", "coding", "easy", "len(lst); lst[4] guarded by length check / IndexError handling"),
    _q("Sort a list in place without creating another list.",
       "python", "coding", "easy", "lst.sort() vs sorted() copy; stability; key functions"),
    _q("Given two lists, count occurrences of a sequence (e.g. [1,1]) inside the first list and report as a dict.",
       "python", "coding", "medium", "Sliding window over zip(l, l[1:]) counting matches; generalise to k-length"),
    _q("Predict the output of tricky Python snippets (mutable default args, aliasing, slicing).",
       "python", "core", "medium", "Mutable default retained across calls; b=a aliases; a[:] copies"),

    # ── Puzzles / behavioral extras from these panels ────────────────────
    _q("You have a 5-litre jar and a 3-litre jar and unlimited water. Measure exactly 4 litres.",
       "puzzles", "applied", "medium",
       "Fill 5, pour into 3 (leaves 2), empty 3, move 2, fill 5, top up 3 → 4 in the 5L jar; state invariants"),
    _q("Give a crisp self-introduction for an embedded interview — structure it.",
       "behavioral", "behavioral", "easy",
       "Current role + domain, 2 quantified highlights, stack summary, why this role — under 90 seconds"),
    _q("Walk through your most recent project in depth: architecture, your exact role, and a code-level detail you owned.",
       "behavioral", "behavioral", "medium",
       "Context → architecture sketch → your components → one deep technical decision with trade-offs → measurable outcome"),
    _q("Which debugging tools have you used across your projects, and give one concrete save for each.",
       "debugging", "behavioral", "medium",
       "JTAG/SWD, GDB, logic analyzer, oscilloscope, CAN analyzer, strace/dmesg — each with a specific bug story"),
]


def company_questions() -> list[dict]:
    """The curated company-asked set (stable order)."""
    return COMPANY_QUESTIONS
