"""EMBEDHUNT AI — Main API Router"""
from fastapi import APIRouter
from app.api.v1 import auth, resume, profile, recommendation, applications, roadmap, interview, dashboard, company, notifications, search, agent, career_twin, feedback, coach, app_version, salary, simulation, code, mentor, report, lab, ai_features

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(app_version.router)
api_router.include_router(career_twin.router)
api_router.include_router(feedback.router)
api_router.include_router(coach.router)
api_router.include_router(resume.router)
api_router.include_router(profile.router)
api_router.include_router(recommendation.router)
api_router.include_router(applications.router)
api_router.include_router(roadmap.router)
api_router.include_router(interview.router)
api_router.include_router(dashboard.router)
api_router.include_router(company.router)
api_router.include_router(notifications.router)
api_router.include_router(search.router)
api_router.include_router(agent.router)
api_router.include_router(salary.router)
api_router.include_router(simulation.router)
api_router.include_router(code.router)
api_router.include_router(mentor.router)
api_router.include_router(report.router)
api_router.include_router(lab.router)
api_router.include_router(ai_features.router)
